### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by birwin88** [FlagX/ha-ledvance-tuya-resync-localkey#33]
`Traceback (most recent call last):
  File "/home/birwin/ledvance/ha-ledvance-tuya-resync-localkey/print-local-keys.py", line 51, in <module>
    main()
  File "/home/birwin/ledvance/ha-ledvance-tuya-resync-localkey/print-local-keys.py", line 42, in main
    for group in api.groups():
                 ^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
`
I'm trying to get the local key for a sylvania smart plug.  Authorization is ok but I'm left with the above.. Is it because the script is unable to get them for that device?

Thanks

**Comment by birwin88** [comment]
Can close.. Resolved by this comment here:  https://community.home-assistant.io/t/ledvance-integration-this-is-how-to-do-it-as-per-08-22/449783/9
